tap "homebrew/cask"
tap "homebrew/cask-versions"

cask "github"
cask "1Password"
cask "Spotify"
cask "visual-studio-code"
cask "iterm2"
cask "firefox-developer-edition"
cask "rectangle"

brew "the_silver_searcher"
brew "fzf"
brew "direnv"
brew "watch"
brew "jq"
brew "youtube-dl"
