#!/usr/bin/env zsh


DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Configuring ZSH  ..."
[[ ! -d ~/.zplug ]] && git clone https://github.com/zplug/zplug ~/.zplug
setopt EXTENDED_GLOB
for rcfile in zshrc zshenv ; do ln -sf ${DOTFILES_DIR}/zsh/${rcfile} ~/.${rcfile} ; done


