#!/usr/bin/env zsh


DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Configuring ZSH  ..."
[[ ! -d ~/.zplug ]] && git clone https://github.com/zplug/zplug ~/.zplug
setopt EXTENDED_GLOB
for rcfile in zshrc zshenv ; do ln -sf ${DOTFILES_DIR}/zsh/${rcfile} ~/.${rcfile} ; done

echo "... git"
ln -sf ${DOTFILES_DIR}/git/gitconfig ~/.gitconfig
ln -sf ${DOTFILES_DIR}/git/gitignore ~/.gitignore


echo "... brew"

[[ ! -f /usr/local/bin/brew ]] && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew bundle

echo "... jvm"
[[ ! -d $HOME/.sdkman ]] && curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk update

