source ~/.zplug/init.zsh

zplug "modules/autosuggestions", from:prezto, as:plugin
zplug "plugins/history-substring-search",   from:oh-my-zsh
zplug "plugins/zsh-syntax-highlighting",   from:oh-my-zsh

zplug "modules/homebrew", from:prezto, as:plugin
zplug "modules/directory", from:prezto, as:plugin
zplug romkatv/powerlevel10k, as:theme, depth:1
zplug "djui/alias-tips", as:plugin
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/direnv", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/fzf", from:oh-my-zsh
zplug "plugins/gcloud", from:oh-my-zsh
zplug "plugins/kubectl", from:oh-my-zsh


# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi


zplug load # --verbose

export EDITOR='vim'


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

